// frontend/vue-app-shell/src/components/app-login.vue
<script setup lang="ts">
import { ref, type Component } from 'vue';
import { useColorMode } from '@vueuse/core';
import { ChevronRight, Lock, LockOpen } from 'lucide-vue-next';

import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"
import { Spinner } from "@/components/ui/spinner"

interface LoginProps {
  ImageLogo?: string
  ImageLogoWhite?: string
  ImageBanner?: string
  loginSend?: (valuez:{ identity: string; password: string }) => void
  HeaderLogin?: Component
  FooterLogin?: Component
  ResetPasswordForm?: Component
}

const props = defineProps<LoginProps>();

const mode = useColorMode();

const showPassword = ref(false);
const loadingButton = ref(false);

const form = ref({
  identity: "",
  password: "",
})

const onFormSubmit = async() => {
  if (!props.loginSend) return true;

  loadingButton.value = true;

  props.loginSend(form.value);

  setTimeout(() => {
    loadingButton.value = false;
  }, 1500)
}

</script>

<template>
  <div class="grid min-h-svh lg:grid-cols-2">
    <div class="flex flex-col gap-4 p-6 md:p-10">
      <div class="flex justify-center gap-2 md:justify-start">
        <img
          v-if="props.ImageLogo && props.ImageLogoWhite"
          :src="mode === 'dark' && ImageLogoWhite ? ImageLogoWhite : ImageLogo"
          alt="Image"
          class="h-12"
        />
        <div v-else>LOGO</div>
      </div>
      <div class="flex flex-1 items-center justify-center">
        <div class="w-full max-w-xs">

          <form @submit.prevent="onFormSubmit" class="flex flex-col gap-6">
    
            <component v-if="props.HeaderLogin" :is="props.HeaderLogin" />

            <div class="grid gap-6">
              <div class="grid w-full max-w-sm items-center gap-1.5">
                <Label for="identity">Identity</Label>
                <Input v-model="form.identity" id="identity" type="text" placeholder="name@example.com" />
              </div>
              <div class="grid w-full max-w-sm items-center gap-1.5">
                <Label for="password">Password</Label>
                <div class="relative">
                  <Input v-model="form.password" id="password" :type="showPassword ? 'text' : 'password'" placeholder="name@example.com" />
                  <Button
                    type="button"
                    variant="ghost"
                    size="sm"
                    class="absolute right-0 top-0 h-full px-3 py-2 hover:bg-transparent"
                    @click="showPassword = !showPassword"
                  >
                    <LockOpen v-if="showPassword" class="size-4" aria-hidden="true" />
                    <Lock v-else class="size-4" aria-hidden="true" />
                  </Button>
                </div>
              </div>

              <Button :type="loadingButton ? 'button' : 'submit'" variant="outline" :disabled="loadingButton">
                <Spinner v-if="loadingButton" />
                <ChevronRight v-else />
                {{ loadingButton ? 'Loading...' : 'Login' }}
              </Button>

              <component v-if="props.FooterLogin" :is="props.FooterLogin" />

            </div>
          </form>

        </div>
      </div>
    </div>
    <div v-if="props.ImageBanner" class="bg-muted relative hidden lg:block">
      <img
        :src="props.ImageBanner"
        alt="Image"
        class="absolute inset-0 h-full w-full object-cover"
      />
    </div>
  </div>
</template>

// embed/react-app-shell/src/components/app-login.tsx
import { type ComponentType, useState } from "react";
import { useTheme } from "@/components/useTheme";

import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"
import { z } from "zod"

import { ChevronRight, Lock, LockOpen } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Spinner } from "@/components/ui/spinner"
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form"

const formSchema = z.object({
  identity: z.string().min(2, {
    message: "Identity Wajib Di Isi",
  }),
  password: z.string().min(2, {
    message: "Password Wajib Di Isi",
  })
})

type LoginFormProps = React.ComponentProps<"form"> & {
  loginSend?: (valuez:{ identity: string; password: string }) => void
  HeaderLogin?: ComponentType
  FooterLogin?: ComponentType
  ResetPasswordForm?: ComponentType
}

function LoginForm({
  loginSend,
  HeaderLogin,
  FooterLogin,
  ResetPasswordForm,
  ...props
}: LoginFormProps) {
  
  const [showPassword, setShowPassword] = useState(false);
  const [loadingButton, setLoadingButton] = useState(false);

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      identity: "",
      password: "",
    },
  })

  function onSubmit(values: z.infer<typeof formSchema>) {
    if (!loginSend) return true;
    
    setLoadingButton(true);

    loginSend(values);

    setTimeout(() => {
      setLoadingButton(false);
    }, 1500)
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="flex flex-col gap-6" {...props}>

        {HeaderLogin && <HeaderLogin />}
        
        <div className="grid gap-6">
          <FormField
            control={form.control}
            name="identity"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Identity</FormLabel>
                <FormControl>
                  <Input placeholder="name@example.com" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          <FormField
            control={form.control}
            name="password"
            render={({ field }) => (
              <FormItem>
                <FormLabel>
                  <span>Password</span>
                  {ResetPasswordForm && <ResetPasswordForm />}
                </FormLabel>
                <FormControl>
                  <div className="relative">
                    <Input
                      type={showPassword ? 'text' : 'password'}
                      className="hide-password-toggle pr-10"
                      {...field}
                    />
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      className="absolute right-0 top-0 h-full px-3 py-2 hover:bg-transparent"
                      onClick={() => setShowPassword((prev) => !prev)}
                    >
                      {showPassword ? (
                        <LockOpen className="h-4 w-4" aria-hidden="true" />
                      ) : (
                        <Lock className="h-4 w-4" aria-hidden="true" />
                      )}
                      <span className="sr-only">{showPassword ? 'Hide password' : 'Show password'}</span>
                    </Button>

                    <style>{`
                        .hide-password-toggle::-ms-reveal,
                        .hide-password-toggle::-ms-clear {
                          visibility: hidden;
                          pointer-events: none;
                          display: none;
                        }
                      `}</style>
                  </div>
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          <Button variant="outline" type={loadingButton ? 'button' : 'submit'} className="w-full" disabled={loadingButton ? true : false}>
            {loadingButton ? <Spinner /> : <ChevronRight />}
            {loadingButton ? 'Loading...' : 'Login' }
          </Button>

          {FooterLogin && <FooterLogin />}

        </div>
      </form>
    </Form>
  )
}


interface LoginProps {
  ImageLogo?: string
  ImageLogoWhite?: string
  ImageBanner?: string
  loginSend: (valuez:{ identity: string; password: string }) => void
  HeaderLogin?: ComponentType
  FooterLogin?: ComponentType
  ResetPasswordForm?: ComponentType
}

export default function AppLogin({
  ImageLogo,
  ImageLogoWhite,
  ImageBanner,
  loginSend,
  HeaderLogin,
  FooterLogin,
  ResetPasswordForm,
}: LoginProps) {
  const { theme } = useTheme();

  return (
    <div className="grid min-h-svh lg:grid-cols-2">
      <div className="flex flex-col gap-4 p-6 md:p-10">
        <div className="flex justify-center gap-2 md:justify-start">
          {ImageLogo && ImageLogoWhite ? <img
            src={theme === "dark" && ImageLogoWhite ? ImageLogoWhite : ImageLogo}
            alt="Image"
            className="h-12"
          /> : "LOGO"}
        </div>
        <div className="flex flex-1 items-center justify-center">
          <div className="w-full max-w-xs">
            <LoginForm 
              loginSend={loginSend} 
              HeaderLogin={HeaderLogin} 
              FooterLogin={FooterLogin} 
              ResetPasswordForm={ResetPasswordForm} 
            />
          </div>
        </div>
      </div>
      {ImageBanner && <div className="bg-muted relative hidden lg:block">
        <img
          src={ImageBanner}
          alt="Image"
          className="absolute inset-0 h-full w-full object-cover"
        />
      </div>}
    </div>
  )
}
