// embed/vue-app-shell/src/components/auth/LoginForm.vue
<script setup lang="ts">
import { ref, type Component } from 'vue';
import { Lock, LockOpen } from 'lucide-vue-next';

import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Button } from "@/components/ui/button"

interface LoginFormProps {
  loginSend?: (valuez:{ identity: string; password: string }) => void
  HeaderLogin?: Component
  FooterLogin?: Component
  ResetPasswordForm?: Component
}

const props = defineProps<LoginFormProps>();

const showPassword = ref(false);
const loadingButton = ref(false);

const form = ref({
  identity: "",
  password: "",
})

const onFormSubmit = async() => {
  loadingButton.value = true;
  console.log(form.value);

  setTimeout(() => {
    loadingButton.value = false;
  }, 1500)
}

</script>

<template>
  <form @submit.prevent="onFormSubmit" class="flex flex-col gap-6">
    
    <component v-if="props.HeaderLogin" :is="props.HeaderLogin" />

    <div class="grid gap-6">
      <div class="grid w-full max-w-sm items-center gap-1.5">
        <Label for="identity">Identity</Label>
        <Input v-model="form.identity" id="identity" type="text" placeholder="name@example.com" />
      </div>
      <div class="grid w-full max-w-sm items-center gap-1.5">
        <Label for="password">Password</Label>
        <div class="relative">
          <Input v-model="form.password" id="password" :type="showPassword ? 'text' : 'password'" placeholder="name@example.com" />
          <Button
            type="button"
            variant="ghost"
            size="sm"
            class="absolute right-0 top-0 h-full px-3 py-2 hover:bg-transparent"
            @click="showPassword = !showPassword"
          >
            <LockOpen v-if="showPassword" class="size-4" aria-hidden="true" />
            <Lock v-else class="size-4" aria-hidden="true" />
          </Button>
        </div>
      </div>

      <Button :type="loadingButton ? 'button' : 'submit'" variant="outline" className="w-full">
        {{ loadingButton ? 'Loading...' : 'Login' }}
      </Button>

      <component v-if="props.FooterLogin" :is="props.FooterLogin" />

    </div>
  </form>
</template>

// embed/react-app-shell/src/components/auth/LoginForm.tsx
import { useState, type ComponentType, type JSX } from "react"
import { zodResolver } from "@hookform/resolvers/zod"
import { useForm } from "react-hook-form"
import { z } from "zod"

import { EyeIcon, EyeOffIcon } from "lucide-react"

import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from "@/components/ui/form"

const formSchema = z.object({
  identity: z.string().min(2, {
    message: "Identity Wajib Di Isi",
  }),
  password: z.string().min(2, {
    message: "Password Wajib Di Isi",
  })
})

type LoginFormProps = React.ComponentProps<"form"> & {
  loginSend?: (valuez:{ identity: string; password: string }) => void
  HeaderLogin?: JSX.Element
  FooterLogin?: ComponentType
  ResetPasswordForm?: ComponentType
}

export function LoginForm({
  loginSend,
  HeaderLogin,
  FooterLogin,
  ResetPasswordForm,
  ...props
}: LoginFormProps) {
  
  const [showPassword, setShowPassword] = useState(false);
  const [loadingButton, setLoadingButton] = useState(false);

  const form = useForm<z.infer<typeof formSchema>>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      identity: "",
      password: "",
    },
  })

  function onSubmit(values: z.infer<typeof formSchema>) {
    if (!loginSend) return true;
    
    setLoadingButton(true);

    loginSend?.(values);

    setTimeout(() => {
      setLoadingButton(false);
    }, 3000)
  }

  return (
    <Form {...form}>
      <form onSubmit={form.handleSubmit(onSubmit)} className="flex flex-col gap-6" {...props}>

        {HeaderLogin ?? null}
        
        <div className="grid gap-6">
          <FormField
            control={form.control}
            name="identity"
            render={({ field }) => (
              <FormItem>
                <FormLabel>Identity</FormLabel>
                <FormControl>
                  <Input placeholder="name@example.com" {...field} />
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />
          <FormField
            control={form.control}
            name="password"
            render={({ field }) => (
              <FormItem>
                <FormLabel>
                  <span>Password</span>
                  {ResetPasswordForm && <ResetPasswordForm />}
                </FormLabel>
                <FormControl>
                  <div className="relative">
                    <Input
                      type={showPassword ? 'text' : 'password'}
                      className="hide-password-toggle pr-10"
                      {...field}
                    />
                    <Button
                      type="button"
                      variant="ghost"
                      size="sm"
                      className="absolute right-0 top-0 h-full px-3 py-2 hover:bg-transparent"
                      onClick={() => setShowPassword((prev) => !prev)}
                    >
                      {showPassword ? (
                        <EyeIcon className="h-4 w-4" aria-hidden="true" />
                      ) : (
                        <EyeOffIcon className="h-4 w-4" aria-hidden="true" />
                      )}
                      <span className="sr-only">{showPassword ? 'Hide password' : 'Show password'}</span>
                    </Button>

                    <style>{`
                        .hide-password-toggle::-ms-reveal,
                        .hide-password-toggle::-ms-clear {
                          visibility: hidden;
                          pointer-events: none;
                          display: none;
                        }
                      `}</style>
                  </div>
                </FormControl>
                <FormMessage />
              </FormItem>
            )}
          />

          {loadingButton ? <Button type="button" variant="ghost" className="w-full" disabled={true}>
            Loading...
          </Button> : <Button type="submit" className="w-full">
            Login
          </Button>}

          {FooterLogin && <FooterLogin />}

        </div>
      </form>
    </Form>
  )
}
