// frontend/react-app-shell/src/components/app-sidebar.tsx
import { type ComponentProps, type ComponentType } from "react"
import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarHeader,
  SidebarRail,
} from "@/components/ui/sidebar"

type AppSidebarProps = ComponentProps<typeof Sidebar> & {
  TeamSwitcher?: ComponentType
  NavMain?: ComponentType
  CardInformation?: ComponentType
  NavUser?: ComponentType
};

export function AppSidebar({ 
  TeamSwitcher,
  NavMain,
  CardInformation,
  NavUser,
  ...props 
}: AppSidebarProps) {
  return (
    <Sidebar collapsible="offcanvas" {...props}>
      <SidebarHeader>
        {TeamSwitcher ? <TeamSwitcher /> : null}
      </SidebarHeader>
      <SidebarContent>
        {NavMain ? <NavMain /> : null}
      </SidebarContent>
      <SidebarFooter>
        {CardInformation ? <CardInformation /> : null}
        {NavUser ? <NavUser /> : null}
      </SidebarFooter>
      <SidebarRail />
    </Sidebar>
  )
}

// embed/vue-app-shell/src/components/app-sidebar.vue
<script setup lang="ts">
import type { SidebarProps } from "@/components/ui/sidebar"

import {
  Sidebar,
  SidebarContent,
  SidebarFooter,
  SidebarHeader,
  SidebarRail,
} from "@/components/ui/sidebar"

const props = withDefaults(defineProps<SidebarProps>(), {
  collapsible: "icon",
})

</script>

<template>
  <Sidebar v-bind="props">
    <SidebarHeader>
      <!-- <TeamSwitcher :teams="data.teams" /> -->
    </SidebarHeader>
    <SidebarContent>
      <!-- <NavMain :items="data.navMain" /> -->
      <!-- <NavProjects :projects="data.projects" /> -->
    </SidebarContent>
    <SidebarFooter>
      <!-- <NavUser :user="data.user" /> -->
    </SidebarFooter>
    <SidebarRail />
  </Sidebar>
</template>
