// embed/react-app-shell/src/components/app-shell.tsx

import { 
  lazy,
  Suspense, 
  useCallback, 
  type ComponentType, 
  type JSX, 
  type ReactNode 
} from "react"
import { Moon, Sun } from "lucide-react"

import { Separator } from "@/components/ui/separator"
import {
  SidebarInset,
  SidebarProvider,
  SidebarTrigger,
} from "@/components/ui/sidebar"
import { Skeleton } from "@/components/ui/skeleton"
import { Button } from "@/components/ui/button"

import { useTheme } from "@/components/useTheme";

import { AppSidebar } from "./app-sidebar"

const LoginView = lazy(() => import("./auth/LoginView"));

type AppShellProps = {
  Breadcrumb?: ComponentType
  TeamSwitcher?: ComponentType
  NavMain?: ComponentType
  CardInformation?: ComponentType
  NavUser?: ComponentType
  PageContent?: () => ReactNode
  AuthChecking?: boolean
  AuthPassed?: boolean
  ImageLogo?: string
  ImageLogoWhite?: string
  ImageBanner?: string
  loginSend?: (valuez:{ identity: string; password: string }) => void
  HeaderLogin?: JSX.Element
  FooterLogin?: ComponentType
  ResetPasswordForm?: ComponentType
}

export default function AppShell({
  Breadcrumb,
  TeamSwitcher,
  NavMain,
  CardInformation,
  NavUser,
  PageContent,
  AuthChecking,
  AuthPassed=false,
  ImageLogo,
  ImageLogoWhite,
  ImageBanner,
  loginSend,
  HeaderLogin,
  FooterLogin,
  ResetPasswordForm,
}: AppShellProps) {
  const { setTheme, theme } = useTheme();
  
  const toggleTheme = useCallback(() => {
    setTheme(theme === "dark" ? "light" : "dark");
  }, [theme, setTheme]);

  const loadingIndicator = <div className="fixed inset-0 flex items-center justify-center">
    <div className="relative w-10 h-10 border-2 border-black/70 border-b-transparent rounded-full animate-spin"></div>
  </div>

  if (AuthChecking) {
    return loadingIndicator;
  }

  if (!AuthPassed) {
    return <Suspense fallback={loadingIndicator}>
      <LoginView 
        ImageLogo={ImageLogo}
        ImageLogoWhite={ImageLogoWhite}
        ImageBanner={ImageBanner}
        loginSend={loginSend}
        HeaderLogin={HeaderLogin}
        FooterLogin={FooterLogin}
        ResetPasswordForm={ResetPasswordForm}
      />
    </Suspense>
  }

  return (
    <SidebarProvider>
      <AppSidebar 
        TeamSwitcher={TeamSwitcher}
        NavMain={NavMain}
        CardInformation={CardInformation}
        NavUser={NavUser}
      />
      <SidebarInset>
        <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12 border-b">
          <div className="flex items-center gap-2 px-4">
            <SidebarTrigger className="-ml-1" />
            <Separator
              orientation="vertical"
              className="mr-2 data-[orientation=vertical]:h-4"
            />
            {Breadcrumb && (
              <Suspense fallback={<Skeleton className="h-[20px] w-[200px]" />}>
                <Breadcrumb />
              </Suspense>
            )}
          </div>
          <div className="ms-auto">
            <Button
              variant="outline"
              size="icon"
              className="group/toggle size-8 me-4"
              onClick={toggleTheme}
            >
              <Sun className="hidden [html.dark_&]:block" />
              <Moon className="hidden [html.light_&]:block" />
              <span className="sr-only">Toggle theme</span>
            </Button>
          </div>
        </header>
        <div className="flex-1 p-4">
          {PageContent && <PageContent />}
        </div>
      </SidebarInset>
    </SidebarProvider>
  )
}

// embed/vue-app-shell/src/components/app-shell.vue
<script setup lang="ts">
import { defineAsyncComponent, type Component, type VNodeChild } from 'vue';
import { useColorMode } from '@vueuse/core';
import { Moon, Sun } from 'lucide-vue-next';

import AppSidebar from "./app-sidebar.vue"
import {
  SidebarInset,
  SidebarProvider,
} from "@/components/ui/sidebar"
import { Button } from '@/components/ui/button';
import LoadingPage from './loading-page.vue';

const LoginView = defineAsyncComponent(() => import('./auth/LoginView.vue'))

interface AppShellProps {
  Breadcrumb?: Component
  TeamSwitcher?: Component
  NavMain?: Component
  CardInformation?: Component
  NavUser?: Component
  PageContent?: () => VNodeChild
  AuthChecking?: boolean
  AuthPassed?: boolean
  ImageLogo?: string
  ImageLogoWhite?: string
  ImageBanner?: string
  loginSend?: (valuez: { identity: string; password: string }) => void
  HeaderLogin?: Component
  FooterLogin?: Component
  ResetPasswordForm?: Component
}

const props = defineProps<AppShellProps>();
// console.log(props.AuthPassed)

const mode = useColorMode();
</script>

<template>
  <LoadingPage v-if="props.AuthChecking" />

  <Suspense v-else-if="typeof props.AuthPassed !== undefined && props.AuthPassed === false">
    <template #default>
      <LoginView 
        :ImageLogo="props.ImageLogo"
        :ImageLogoWhite="props.ImageLogoWhite"
        :ImageBanner="props.ImageBanner"
        :loginSend="props.loginSend"
        :HeaderLogin="props.HeaderLogin"
        :FooterLogin="props.FooterLogin"
        :ResetPasswordForm="props.ResetPasswordForm"
      />
    </template>
    <template #fallback>
      <div class="flex items-center justify-center h-screen">
        <div class="w-10 h-10 border-2 border-black border-b-transparent rounded-full animate-spin"></div>
      </div>
    </template>
  </Suspense>

  <SidebarProvider v-else>
    <AppSidebar />
    <SidebarInset>
      <header className="flex h-16 shrink-0 items-center gap-2 transition-[width,height] ease-linear group-has-data-[collapsible=icon]/sidebar-wrapper:h-12 border-b">
        <div class="flex items-center gap-2 px-4">
          
        </div>
        <div className="ms-auto">
          <Button
            variant="outline"
            size="icon"
            @click="mode = mode === 'dark' ? 'light' : 'dark'"
          >
            <Sun v-if="mode === 'dark'" className="hidden [html.dark_&]:block" />
            <Moon v-else className="hidden [html.light_&]:block" />
            <span className="sr-only">Toggle theme</span>
          </Button>
        </div>
      </header>
      <div class="flex flex-1 flex-col gap-4 p-4">
        <div class="grid auto-rows-min gap-4 md:grid-cols-3">
          <div class="aspect-video rounded-xl bg-muted/50" />
          <div class="aspect-video rounded-xl bg-muted/50" />
          <div class="aspect-video rounded-xl bg-muted/50" />
        </div>
        <div class="min-h-[100vh] flex-1 rounded-xl bg-muted/50 md:min-h-min" />
      </div>
    </SidebarInset>
  </SidebarProvider>
</template>
